plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.html2apk.stub'
    compileSdk 34

    defaultConfig {
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    flavorDimensions 'slot'
    productFlavors {
        stub1 {
            dimension 'slot'
            applicationId 'com.html2apk.stub1'
        }
        stub2 {
            dimension 'slot'
            applicationId 'com.html2apk.stub2'
        }
        stub3 {
            dimension 'slot'
            applicationId 'com.html2apk.stub3'
        }
        stub4 {
            dimension 'slot'
            applicationId 'com.html2apk.stub4'
        }
        stub5 {
            dimension 'slot'
            applicationId 'com.html2apk.stub5'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.10.0'
}
